// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLastFile():Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function GetStats():Promise<main.Stats>;

export function Greet(arg1:string):Promise<string>;

export function LoadFile(arg1:string):Promise<main.LoadResult>;

export function OpenFileDialog():Promise<string>;

export function SaveLastFile(arg1:string):Promise<void>;

export function SearchLogs(arg1:main.SearchQuery):Promise<main.SearchResult>;

export function SetSettings(arg1:main.AppSettings):Promise<void>;
