// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomFormat(arg1) {
  return window['go']['main']['App']['AddCustomFormat'](arg1);
}

export function DeleteCustomFormat(arg1) {
  return window['go']['main']['App']['DeleteCustomFormat'](arg1);
}

export function GetCustomFormats() {
  return window['go']['main']['App']['GetCustomFormats']();
}

export function GetDateRange() {
  return window['go']['main']['App']['GetDateRange']();
}

export function GetLastFile() {
  return window['go']['main']['App']['GetLastFile']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemResource() {
  return window['go']['main']['App']['GetSystemResource']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RefreshLogs() {
  return window['go']['main']['App']['RefreshLogs']();
}

export function SaveLastFile(arg1) {
  return window['go']['main']['App']['SaveLastFile'](arg1);
}

export function SearchLogs(arg1) {
  return window['go']['main']['App']['SearchLogs'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function TestCustomFormat(arg1, arg2) {
  return window['go']['main']['App']['TestCustomFormat'](arg1, arg2);
}

export function UpdateCustomFormat(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomFormat'](arg1, arg2);
}
