// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';
import {main} from '../models';

export function AddCustomFormat(arg1:parser.CustomFormat):Promise<void>;

export function DeleteCustomFormat(arg1:string):Promise<void>;

export function GetCustomFormats():Promise<Array<parser.CustomFormat>>;

export function GetDateRange():Promise<main.DateRange>;

export function GetLastFile():Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function GetStats():Promise<main.Stats>;

export function GetSystemResource():Promise<main.SystemResource>;

export function Greet(arg1:string):Promise<string>;

export function LoadFile(arg1:string):Promise<main.LoadResult>;

export function OpenFileDialog():Promise<string>;

export function RefreshLogs():Promise<main.RefreshResult>;

export function SaveLastFile(arg1:string):Promise<void>;

export function SearchLogs(arg1:main.SearchQuery):Promise<main.SearchResult>;

export function SetSettings(arg1:main.AppSettings):Promise<void>;

export function TestCustomFormat(arg1:string,arg2:string):Promise<main.TestFormatResult>;

export function UpdateCustomFormat(arg1:string,arg2:parser.CustomFormat):Promise<void>;
